name: "21st IFIP Summer School on Privacy and Identity Management"
title: "21st IFIP Summer School"
title_separator: "-"
subtitle: "on Privacy and Identity Management (August 10-14, 2026, Leuven)"
description: >- # this means to ignore newlines until "baseurl:"
  Website for IFIP Summer School on Privacy and Identity Management.
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# TZ needed?
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-include-cache

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/IFIP_PrivacyIdM"
    - label: "Privacy Policy"
      url: "/privacy_policy/"


atom_feed:
  hide: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
